version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    volumes:
      - "./adguardhome/workdir:/opt/adguardhome/work"
      - "./adguardhome/confdir:/opt/adguardhome/conf"
    ports:
      - "3000:3000"
      - "8080:80"
    restart: always
    environment:
      - TZ=Asia/Chongqing
    networks:
      ssnet:
        ipv4_address: 10.9.2.2
  v2ray:
    image: v2ray/official
    restart: always
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
    environment:
      - TZ=Asia/Chongqing
    networks:
      ssnet:
        ipv4_address: 10.9.2.3
    dns:
      - 10.9.2.2
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./www:/var/www
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Chongqing
    networks:
      ssnet:
        ipv4_address: 10.9.2.4
networks:
  ssnet:
    ipam:
      config:
        - subnet: 10.9.2.0/24
